language: node_js
node_js: stable
sudo: false
install: true
os:
- linux
before_script:
- npm install
- npm install -g coveralls nyc
script:
- npm run test && npm run lint
after_success:
- nyc report --reporter=text-lcov | coveralls
deploy:
  provider: npm
  email: huihangkin@gmail.com
  api_key:
    secure: iAzU1oagRpX2ewU2vGP0QUOC6gzAEP1LRE9wGraI+kmlztZMQGY/WUr6rBf23sE3DE9DDbwDaLte5ZWIbJb6DmG8biH+fhK7sGF0iCmeV2BQxMIFrujl8E38k5SSezD4tFITo9OKLRgaxUtYIyQNUNGohtQR0JM0B4u9jHmtryStNUO3PPkCVzvQ4+8bUs+Xs5a9/LnFwJX8bXo3pXM4L+0EGnr+7W7GistMrEKnjN9atsSaLefN58V/720/4OkwO3cc2wHp/jpZnztt+TCqjDQwmunDhP//W5ruIQ7kRb/E91aTlu+p5Jd/QEA1fViPNZ0qrmeoiNZEXdIvIps8jo6+JZEg/5RivKNoad6WN7n27K2sc2a94763Bho5z8MovlZ5n4XheQDidFE7GbBgCm63daKbmtDYn8PRjsU2hlLD/fJ8fhVioQuNL9cj2GjRwIVe2ZQYA70OQ34H0DG6UOA1xgzDR0oledkWxu4UVUYPffKoBOYhc3yrtCzI3b0pV/9opI4y0ZgFfC0SFPqBzg0ICCi5uENqs/wLn2OcfXs+/X8izBls2c3wap05kvU6MsKG93x62tvboJveDEQXqOYwRizz8mq5gEYe19YK3szxY4b5wacWk2OATOzWgLb/8oe13J3HbZ3Xp82VZA8flk8IhCDHWlzEBnAl3aWuVGo=
  on:
    tags: true
    repo: goldenbearkin/test-npm-publish
